version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: doc_collab_db_user
      POSTGRES_PASSWORD: doc_collab_db_pass 
      POSTGRES_DB: doc_collab_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: